# vim:fileencoding=utf-8:foldmethod=marker

# Fonts 

#: kitty has very powerful font management. You can configure
#: individual font faces and even specify special fonts for particular
#: characters.

font_family      Iosevka NF
# bold_font        auto
# italic_font      auto
# bold_italic_font auto

font_size 20.0

scrollback_lines 2000
scrollbar always


# scrollback_pager less --chop-long-lines --RAW-CONTROL-CHARS +INPUT_LINE_NUMBER

#: Program with which to view scrollback in a new window. The
#: scrollback buffer is passed as STDIN to this program. If you change
#: it, make sure the program you use can handle ANSI escape sequences
#: for colors and text formatting. INPUT_LINE_NUMBER in the command
#: line above will be replaced by an integer representing which line
#: should be at the top of the screen. Similarly CURSOR_LINE and
#: CURSOR_COLUMN will be replaced by the current cursor position or
#: set to 0 if there is no cursor, for example, when showing the last
#: command output.

#: If you would rather use neovim to view the scrollback, use
#: something like this::

# scrollback_pager nvim --cmd 'set eventignore=FileType' +'nnoremap q ZQ' +'call nvim_open_term(0, {})' +'set nomodified nolist' +'$' -

repaint_delay 15
input_delay 3
sync_to_monitor yes

# Terminal bell 
enable_audio_bell no

# Tab bar 
tab_bar_edge bottom

tab_bar_style powerline
tab_bar_align center
tab_bar_min_tabs 1
tab_powerline_style round

editor nvim

shell_integration disabled

clear_all_shortcuts yes
allow_remote_control yes
listen_on unix:/tmp/kittyrpc

#: Increase font size

# map kitty_mod+equal  change_font_size all +2.0
map ctrl+q>plus   change_font_size all +1.0
map ctrl+q>minus  change_font_size all -1.0
map ctrl+q>equal change_font_size all 0



## TABS
map ctrl+q>c launch --type tab
map ctrl+q>ctrl+c launch --type tab --cwd current

# Last tab
map alt+; goto_tab 0

map ctrl+q>, set_tab_title

map ctrl+q>1 goto_tab 1
map ctrl+q>2 goto_tab 2
map ctrl+q>3 goto_tab 3
map ctrl+q>4 goto_tab 4
map ctrl+q>5 goto_tab 5

#: Unicode input

# map kitty_mod+u    kitten unicode_input
# map ctrl+cmd+space kitten unicode_input

#: Open the kitty command shell
map ctrl+q>: kitty_shell window


#: Reload kitty.conf
map ctrl+q>r load_config_file

# Layouts
enabled_layouts tall,stack
map ctrl+shift+, resize_window narrower
map ctrl+shift+. resize_window wider

# Tab title template with "Zomm" window suppor
tab_title_template "{fmt.fg.red}{fmt.fg.tab}{index}: {title}{' *Z' if layout_name == 'stack' else ''}"


## WINDOWS RELATED
# Zoom windows (https://andrew.hau.st/blog/from-tmux-to-kitty/#resizing-windows)
map ctrl+q>z combine : toggle_layout stack : scroll_prompt_to_bottom

map ctrl+q>shift+\ new_window
map ctrl+q>k close_window

map alt+h previous_window 
map alt+l next_window

map ctrl+q>o close_other_windows_in_tab

map ctrl+q>f move_window_to_top
map ctrl+q>ctrl+w focus_visible_window
map ctrl+q>w focus_visible_window

# Nice
scrollback_pager nvim -u NONE -R -M -c 'lua dofile("$HOME/.config/kitty/kitty-pager.lua")(INPUT_LINE_NUMBER)'

map ctrl+q>] show_scrollback
map ctrl+v> paste_from_clipboard



# BEGIN_KITTY_THEME
# kanagawabones
include current-theme.conf
# END_KITTY_THEME
