return {
  "NeogitOrg/neogit",
  dependencies = {
    "nvim-lua/plenary.nvim",         -- required
    "sindrets/diffview.nvim",        -- optional - Diff integration
    "ibhagwan/fzf-lua",              -- optional
  },
  opts = {
      use_default_keymaps = false,
      integrations = {
          fzf_lua = true
      },
      kind = "replace",
      mappings = {
          commit_editor = {
              ["<localleader>q"] = "Close",
              ["<localleader>a"] = "Abort",
              ["<localleader>k"] = "PrevMessage",
              ["<localleader>j"] = "NextMessage",
              ["<localleader>r"] = "ResetMessage",
              ["<localleader>a"] = "Abort",
          },
          commit_editor_I = {
              ["<localleader>s"] = "Submit",
              ["<localleader>a"] = "Abort",
          },
          rebase_editor = {
              ["p"]          = "Pick",
              ["r"]          = "Reword",
              ["e"]          = "Edit",
              ["s"]          = "Squash",
              ["f"]          = "Fixup",
              ["x"]          = "Execute",
              ["d"]          = "Drop",
              ["b"]          = "Break",
              ["q"]          = "Close",
              ["<cr>"]       = "OpenCommit",
              ["gk"]         = "MoveUp",
              ["gj"]         = "MoveDown",
              ["<localleader>s"] = "Submit",
              ["<localleader>a"] = "Abort",
              ["[c"]         = "OpenOrScrollUp",
              ["]c"]         = "OpenOrScrollDown",
          },
          rebase_editor_I = {
              ["<localleader>s"] = "Submit",
              ["<localleader>a"] = "Abort",
          },

          finder = {
              ["<cr>"]               = "Select",
              ["<localleader>q"]     = "Close",
              ["<c-n>"]              = "Next",
              ["<c-p>"]              = "Previous",
              ["<down>"]             = "Next",
              ["<up>"]               = "Previous",
              ["<tab>"]              = "InsertCompletion",
              ["<c-y>"]              = "CopySelection",
              ["<space>"]            = "MultiselectToggleNext",
              ["<s-space>"]          = "MultiselectTogglePrevious",
              ["<c-j>"]              = "NOP",
              ["<ScrollWheelDown>"]  = "ScrollWheelDown",
              ["<ScrollWheelUp>"]    = "ScrollWheelUp",
              ["<ScrollWheelLeft>"]  = "NOP",
              ["<ScrollWheelRight>"] = "NOP",
              ["<LeftMouse>"]        = "MouseClick",
              ["<2-LeftMouse>"]      = "NOP",
          },

          popup = {
              ["?"] = "HelpPopup",
              ["A"] = "CherryPickPopup",
              ["d"] = "DiffPopup",
              ["M"] = "RemotePopup",
              ["P"] = "PushPopup",
              ["X"] = "ResetPopup",
              ["Z"] = "StashPopup",
              ["i"] = "IgnorePopup",
              ["t"] = "TagPopup",
              ["b"] = "BranchPopup",
              ["B"] = "BisectPopup",
              ["w"] = "WorktreePopup",
              ["c"] = "CommitPopup",
              ["f"] = "FetchPopup",
              ["l"] = "LogPopup",
              ["m"] = "MergePopup",
              ["p"] = "PullPopup",
              ["r"] = "RebasePopup",
              ["v"] = "RevertPopup",
          },

          status = {
              ["j"]      = "MoveDown",
              ["k"]      = "MoveUp",
              ["o"]      = "OpenTree",
              ["q"]      = "Close",
              ["I"]      = "InitRepo",
              ["1"]      = "Depth1",
              ["2"]      = "Depth2",
              ["3"]      = "Depth3",
              ["4"]      = "Depth4",
              ["Q"]      = "Command",
              ["<tab>"]  = "Toggle",
              ["x"]      = "Discard",
              ["s"]      = "Stage",
              ["S"]      = "StageUnstaged",
              ["<c-s>"]  = "StageAll",
              ["u"]      = "Unstage",
              ["K"]      = "Untrack",
              ["U"]      = "UnstageStaged",
              ["y"]      = "ShowRefs",
              ["$"]      = "CommandHistory",
              ["Y"]      = "YankSelected",
              ["<c-r>"]  = "RefreshBuffer",
              ["<cr>"]   = "GoToFile",
              ["<s-cr>"] = "PeekFile",
              ["<c-v>"]  = "VSplitOpen",
              ["<c-x>"]  = "SplitOpen",
              ["<c-t>"]  = "TabOpen",
              ["{"]      = "GoToPreviousHunkHeader",
              ["}"]      = "GoToNextHunkHeader",
              ["[c"]     = "OpenOrScrollUp",
              ["]c"]     = "OpenOrScrollDown",
              ["<c-k>"]  = "PeekUp",
              ["<c-j>"]  = "PeekDown",
          },
      }
  }
}
