# theme = "modus_operandi_tinted"
theme = "kanagawa"

##########
# EDITOR #
##########

[editor]
scrolloff = 8
cursorcolumn = true
completion-timeout = 100
completion-replace = true
color-modes = true
auto-pairs = false
true-color = true

[editor.statusline]
left = ["spinner", "file-base-name", "read-only-indicator", "file-modification-indicator"]
center = ["mode"]
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.cursor-shape]
normal = "block"
insert = "bar"
select = "underline"

###########
# KEYMAPS #
###########

[keys.insert]
"C-c" = "normal_mode"


[keys.normal]
"$" = "goto_line_end"
0 = "goto_first_nonwhitespace"
G = "goto_last_line"
"C-c" = "normal_mode"
"C-q" = "no_op"

[keys.select]
"$" = "goto_line_end"
0 = "goto_first_nonwhitespace"
G = "goto_last_line"
"C-c" = "normal_mode"


[keys.normal."space"]
f = "file_picker_in_current_directory"
d = ":wq"
D = "file_explorer_in_current_directory"
r = "global_search"
a = "buffer_picker"

[keys.normal.g]
r = "rename_symbol"

[keys.normal."space".o]
o = ":run-shell-command realpath %{buffer_name}"
r = [":config-reload", ":reload-all"]
d = ":config-open"

