# theme = "modus_operandi_tinted"
theme = "kanagawa"

##########
# EDITOR #
##########

[editor]
scrolloff = 8
cursorcolumn = true
rulers = [100]
completion-timeout = 100
completion-replace = true
color-modes = true
auto-pairs = false
true-color = true
text-width = 80
gutters = ["diagnostics", "line-numbers", "spacer"]
end-of-line-diagnostics = "hint"
popup-border = "all"
jump-label-alphabet = "jklasd;iomcfrewxnhbvguytqp"
clipboard-provider = "wayland"

[editor.inline-diagnostics]
cursor-line = "hint"
other-lines = "hint"

[editor.soft-wrap]
enable = true

[editor.lsp]
display-inlay-hints = true
display-progress-messages = true

[editor.statusline]
left = [
  "spinner",
  "file-base-name",
  "read-only-indicator",
  "file-modification-indicator",
]
center = ["mode"]
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.cursor-shape]
normal = "block"
insert = "bar"
select = "underline"

###########
# KEYMAPS #
###########

[keys.insert]
C-c = "normal_mode"
C-m = "insert_newline"

[keys.normal]
"$" = "goto_line_end"
0 = "goto_line_start"
L = "goto_line_end"
H = "goto_first_nonwhitespace"
G = "goto_last_line"
C-c = "normal_mode"
C-q = "no_op"
x = "extend_to_line_bounds"
X = "extend_line_below"
C-d = "half_page_down"
C-u = "half_page_up"
A-k = [
  "extend_to_line_bounds",
  "delete_selection",
  "move_line_up",
  "paste_before",
]
A-j = ["extend_to_line_bounds", "delete_selection", "paste_after"]
C-k = ":buffer-close!"
tab = "no_op"

[keys.select]
"$" = "goto_line_end"
0 = "goto_line_start"
L = "goto_line_end"
H = "goto_first_nonwhitespace"
G = "goto_last_line"
"C-c" = "normal_mode"
"C-q" = "no_op"
x = "extend_to_line_bounds"
X = "extend_line_below"
"C-d" = "half_page_down"
"C-u" = "half_page_up"


[keys.normal."space"]
f = "file_picker_in_current_directory"
F = "file_picker_in_current_buffer_directory"

i = [
  ":set inline-diagnostics.cursor-line hint",
  ":set inline-diagnostics.other-lines hint",
  ":set lsp.display-inlay-hints true",
  ":echo [Inline] Set to true / hint",
]

I = [
  ":set inline-diagnostics.cursor-line disable",
  ":set inline-diagnostics.other-lines disable",
  ":set lsp.display-inlay-hints false",
  ":echo [Inline] Set to false / disable",
]

# Yazi - Buffer
d = [
  ':sh rm -f /tmp/yazi-file',
  ':sh rm -f /tmp/yazi-cwd',
  ':insert-output yazi "%sh{dirname %{buffer_name}}" --chooser-file=/tmp/yazi-file --cwd-file=/tmp/yazi-cwd',
  ':sh printf "\x1b[?1049h\x1b[?2004h" > /dev/tty',
  ':open %sh{cat /tmp/yazi-file}',
  ':cd %sh{cat /tmp/yazi-cwd}',
  ':redraw',
]

# Yazi - Current directory
D = [
  ':sh rm -f /tmp/yazi-file',
  ':sh rm -f /tmp/yazi-cwd',
  ':insert-output yazi "%sh{git -C %sh{pwd} rev-parse --show-toplevel 2>/dev/null || echo %sh{pwd}}" --chooser-file=/tmp/yazi-file --cwd-file=/tmp/yazi-cwd',
  ':sh printf "\x1b[?1049h\x1b[?2004h" > /dev/tty',
  ':open %sh{cat /tmp/yazi-file}',
  ':cd %sh{cat /tmp/yazi-cwd}',
  ':redraw',
]

# Change directory to current git root or do nothing
"." = ':cd "%sh{git -C %sh{dirname %{buffer_name}} rev-parse --show-toplevel 2>/dev/null || echo %sh{pwd}}"'


# Find man pages
m = [
  ':sh %sh{fzf-man}',
  ':vnew',
  ':insert-output man %sh{cat /tmp/fzf-man}',
  ':goto 1',
]

# Tmux integration for terminal usage
U = ':sh hx-tmux %sh{pwd}'

# close other
O = ":buffer-close-others!"

# Gitu
g = ':sh tmux display-popup -d "#{pane_current_path}" -h 95%% -w 95%% -E "gitu"'

# Zk
w = ":open ~/personal/notes/zettels/"

q = "@%:pipe fmt --uniform-spacing --width=100 --split-only"

r = "global_search"
a = "buffer_picker"
G = "no_op"
b = "diagnostics_picker"
"/" = "no_op"

[keys.normal.g]
r = "rename_symbol"
c = "toggle_comments"
a = "code_action"
h = "hover"
m = "goto_last_modified_file"
t = "goto_type_definition"
b = "goto_reference"


[keys.select.g]
c = "toggle_comments"

[keys.normal.space.l]

# Zk keys
# Create a new note
a = ":open %sh{zk new --no-input --print-path --title='%{selection}'}"

# Create a new source note
s = ":open %sh{zk new --no-input --print-path --title='%{selection}' --template=source.md}"

# Backlinks: Show linked notes to selected one
f = [
':sh basename -s .md %{buffer_name} > /tmp/zk-unique',
':vnew',
":insert-output zk list -l '%sh{cat /tmp/zk-tmp}' -f '{{abs-path}}' -d'\n' -q --header='# Backlinks to %sh{basename -s .md %sh{cat /tmp/zk-unique}}\n\n'",
":lang markdown",
':sh rm -f /tmp/zk-unique'
]

# Show Orphan nodes
o = [
':vnew',
":insert-output zk list --orphan -f '{{abs-path}}' -d'\n' -q --header='# Orphan notes\n\n'",
":lang markdown",
]

# Show Broken links notes
b = [
':vnew',
":insert-output zk list --broken-links -f '{{abs-path}}' -d'\n' -q --header='# Notes with broken links:\n\n'",
":lang markdown",
]

I = [
  ':new',
  ':insert-output LC_ALL=C tr -dc a-z0-9 </dev/urandom | fold -w 6 | head -n 1',
  'select_all',
  'yank_to_clipboard',
  ':buffer-close!',
  'paste_clipboard_after',
  ':move "%sh{dirname %{buffer_name}}/%sh{wl-paste}-%sh{basename %{buffer_name}}"',
  ':lang markdown'
  # ':echo '%sh{dirname %{buffer_name}}"',
]

# Edit last modified note
l = ':open %sh{zk edlast-path}'


[keys.select.space.l]
# Zk keys
a = ":open %sh{zk new --no-input --print-path --title='%{selection}'}"                      # note
s = ":open %sh{zk new --no-input --print-path --title='%{selection}' --template=source.md}" # source 
f = ":echo %sh{zk list -l '%sh{basename %{buffer_name} .md}' -f {{abs-path}} -d' ' -q}" # open related


[keys.normal."space".o]
o = "@:echo <C-r>%<ret>"
r = [":config-reload", ":reload-all"]
d = ":config-open"
