(load "~/.config/emacs/plugins/general.el")
(load "~/.config/emacs/plugins/undo-fu.el")
(load "~/.config/emacs/plugins/evil.el")
(load "~/.config/emacs/plugins/magit.el")
(load "~/.config/emacs/plugins/hl-todo.el")
(load "~/.config/emacs/plugins/helpful.el")
;; (load "~/.config/emacs/plugins/vertico.el")
;; (load "~/.config/emacs/plugins/consult.el")
(load "~/.config/emacs/plugins/marginalia.el") 
(load "~/.config/emacs/plugins/corfu.el")
(load "~/.config/emacs/plugins/ivy.el")
(load "~/.config/emacs/plugins/counsel.el")
(load "~/.config/emacs/plugins/tools.el")
(load "~/.config/emacs/plugins/projectile.el")
(load "~/.config/emacs/plugins/doom-modeline.el")
(load "~/.config/emacs/plugins/org.el")
(load "~/.config/emacs/plugins/programming.el")
