[env]
TERM = "xterm-256color"

[font]
size = 18.0

[font.bold]
family = "Iosevka Nerd Font Mono"
style = "Bold"

[font.italic]
family = "Iosevka Nerd Font Mono"
style = "Bold Italic"

[font.normal]
family = "Iosevka Nerd Font Mono"
style = "Regular"

[[keyboard.bindings]]
chars = "w \r"
key = "F"
mode = "~Vi"
mods = "Control"

[scrolling]
history = 10000

[shell]
args = ["--login"]
program = "/run/current-system/sw/bin/bash"

[window]
decorations = "none"
decorations_theme_variant = "Dark"
opacity = 0.95
option_as_alt = "OnlyLeft"
startup_mode = "Maximized"

[window.padding]
x = 0
y = 2
