[[keyboard.bindings]]
chars = "w \r"
key = "S"
mode = "~Vi"
mods = "Control"

[terminal]

[env]
TERM = "xterm-256color"

[font]
size = 12.0

[font.bold]
family = "Meslo LGL Nerd Font Mono"
style = "Bold"

[font.italic]
family = "Meslo LGL Nerd Font Mono"
style = "Bold Italic"

[font.normal]
family = "Meslo LGM Nerd Font Mono"
style = "Regular"

[scrolling]
history = 10000

[terminal.shell]
args = ["--login"]
program = "/run/current-system/sw/bin/bash"

[window]
decorations = "none"
decorations_theme_variant = "Dark"
opacity = 0.95
option_as_alt = "OnlyLeft"
startup_mode = "Maximized"

[window.padding]
x = 0
y = 2

[keyboard]
