[terminal]

[env]
TERM = "xterm-256color"

[font]
size = 10.0

[font.normal]
family = "Iosevka NF"

[scrolling]
history = 10000

[terminal.shell]
args = ["--login"]
program = "/run/current-system/sw/bin/bash"

[window]
decorations = "None"
decorations_theme_variant = "Dark"
opacity = 0.55
option_as_alt = "OnlyLeft"
startup_mode = "Maximized"

[window.padding]
x = 0
y = 0

[mouse]
hide_when_typing = true
