# ~/.profile: executed by the command interpreter for login shells.
# This file is not read by bash(1), if ~/.bash_profile or ~/.bash_login
# exists.
# see /usr/share/doc/bash/examples/startup-files for examples.
# the files are located in the bash-doc package.

# the default umask is set in /etc/profile; for setting the umask
# for ssh logins, install and configure the libpam-umask package.
#umask 022

if [ -f "$HOME/.bashrc" ]; then
    . "$HOME/.bashrc"
fi

# set PATH so it includes user's private bin if it exists
if [ -d "$HOME/bin" ] ; then
    PATH="$HOME/bin:$PATH"
fi

# set PATH so it includes user's private bin if it exists
if [ -d "$HOME/.local/bin" ] ; then
    PATH="$HOME/.local/bin:$PATH"
fi

PATH="$PATH:/usr/sbin"

# Include cargo (rust) environment if exists
if [ -d "$HOME/.cargo/env" ] ; then
    . "$HOME/.cargo/env"
fi

export NVM_DIR="$([ -z "${XDG_CONFIG_HOME-}" ] && printf %s "${HOME}/.nvm" || printf %s "${XDG_CONFIG_HOME}/nvm")"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" # This loads nvm

export PATH=$PATH:/usr/local/go/bin

# Include Java JDK (OpenJDK)
if [ -d "/opt/software/openjdk-22/" ] ; then
    export JAVA_HOME=/opt/software/openjdk-22
    export PATH=$PATH:/opt/software/openjdk-22/bin
fi

# Include ADB (Android Platform Tools)
if [ -d "/opt/software/android-platform-tools/" ] ; then
    export PATH=$PATH:/opt/software/android-platform-tools
fi

# Include Golang
if [ $(command -v go) ] ; then
    export GOPATH=$HOME/.local/share/go
    export PATH=$PATH:$GOPATH/bin
fi


# Include Godot 
if [ -d "/opt/software/godot" ] ; then
    export PATH=$PATH:/opt/software/godot
fi


if [[ $(uname -s) == "Darwin" ]]; then
    eval "$(/opt/homebrew/bin/brew shellenv)"
    export BASH_SILENCE_DEPRECATION_WARNING=1
    if [[ -d "/opt/homebrew/opt/openjdk/bin" ]]; then
        export PATH="/opt/homebrew/opt/openjdk/bin:$PATH"
    fi
fi


