[terminal]

[env]
term = "alacritty"
TERM = "alacritty"

[font]
size = 18.0

[font.normal]
family = "Iosevka NF"

[scrolling]
history = 10000

[terminal.shell]
args = ["--login"]
program = "/run/current-system/sw/bin/bash"

[window]
decorations = "None"
decorations_theme_variant = "Dark"
opacity = 0.96
option_as_alt = "OnlyLeft"
startup_mode = "Maximized"

[window.padding]
x = 0
y = 10

[mouse]
hide_when_typing = true

# Kanagawa Wave Alacritty Colors
[general]
import=[
# "~/personal/dotfiles/files/alacritty-themes/kanagawa_wave.toml"
"alacritty-themes/miasma.toml" # <--- 1
# "~/personal/dotfiles/files/alacritty-themes/gruvbox_dark.toml" <-- 2
# "~/personal/dotfiles/files/alacritty-themes/nightfly.toml" # <--- 3
# "~/personal/dotfiles/files/alacritty-themes/solarized_osaka.toml" # <--- 4
]
